### ISSUE TITLE
Adding access level for collections

### ISSUE THREAD

**Issue by DMEthier** [BirdStudiesCanada/naturecounts#3]
The following features could be added to naturecounts: 

nc_counts ()  - would be good to include the access level for each collection 

nc_data_dl () - when using sqlite option it would be good if the resulting file was placed in the working directory rather than C:\User\name\Documents

Thanks!

**Comment by denislepage** [comment]
Agreed on the working directory, and perhaps having a dir option to specify the folder?

**Comment by steffilazerte** [comment]
Hmm, that's odd, it should be in the working directory. Can you use `getwd()` to ensure that the working directory is where you think it is (just to double check?)

```
getwd()
nc_data_dl(..., sql_db = "test")
getwd() # Redundant, but just to make sure nothing odd is going on
```

Right now you can select where the file will go by using
- `sql_db = "test"` Creates "test.nc" in current directory
- `sql_db = "../test"` Creates "test.nc" in the upper level directory
- `sql_db = "data/test"` Creates "test.nc" in the current directory in the folder `data`, assuming that folder exists

But this isn't clear in the examples and it also isn't as smart as it could be (i.e., it fails unhelpfully if the directory doesn't exist).

Should I try to fix/clarify this before the SCO-SOC conference next week?

**Comment by steffilazerte** [comment]
Regarding "nc_counts () - would be good to include the access level for each collection"

What kind of access level do you mean? If, for example, you supply a username, you will get a "yes/no" access column:

```
> nc_count(username = "sample", show = "all")
    access            collection nrecords
1      yes              ABATLAS1   123364
2      yes              ABATLAS2   201398
3      yes            ABBIRDRECS   357264
4       no                ATOWLS      367
5      yes                   BBS  5735895
6      yes             BBS50-CAN  3219534
7      yes         BBS50-US-EAST  8067776
8      yes         BBS50-US-WEST  8701116
9      yes         BCATLAS1BE_DO    41412
10     yes        BCATLAS1BE_RAW   344433
11     yes       BCATLAS1BE_SUMM   165485
12     yes            BCATLAS1PC   260647
13      no            BCATLAS1RC    21884
14      no               BCBEACH     7263
15      no                 BCCWS   346475
16     yes                  BCMA    11291
17      no                BCOWLS    27149
```

I assumed that for most users, this is what they would like to know. I could add an option to return actual access levels (i.e. the ranking?). Is that what you were referring to?

**Comment by DMEthier** [comment]
The access level ranges from 0-5, and is found on the web portal here: https://www.birdscanada.org/birdmon/default/datasets.jsp. If this value was reported when using the nc_count () function, the user would know if they needed to make a request (level 3-4)  through the web portal, or not (level 5). This is somewhat redundant to the 'yes' and 'no' example you provided, since I assume the 'no' are all level 0-4 and the 'yes' are level 5?

**Comment by steffilazerte** [comment]
Glad the sqlite database is behaving!

As for the access levels, I double checked and the API returns the access for that user (yes/no), which is different from access level as it includes whether or not that user has permissions for the data. The `meta_collections()` function returns a `akn_level` (access level), so that data is available and I could add it in. 

However, for users, I wonder if it might be better to summarize and combine the User's access with the access level to make that information directly relevant. For example, we could expand on the access column to have three different levels:

1) "accessible" (currently "yes")
  Already have access (either levels 5, or levels 3/4 if previously requested)

2) "accessible upon request" (currently "no")
  Could request access (levels 3, 4 which haven't been previously requested)

3) "inaccessible" (currently "no")
  Data will not be provided, even upon request (levels 1, 2)

Does this sound useful? Have I understood the meaning of the different access levels?

**Comment by DMEthier** [comment]
Yes. I think that would be very useful.

**Comment by denislepage** [comment]
Sounds good, I think that’s an improvement. One thing to be careful though is that having a request approved doesn’t necessarily grant you access to the whole dataset.

So “accessible” for level 3 and 4 would really only apply to people who have blanket access to the dataset (mostly for admins and coordinators).

**Comment by steffilazerte** [comment]
Okay, so I haven't combined the Web requests into the `nc_count()` function (way too complicated), but I have added access:
```
> nc_count(username = "sample", show = "all")
               collection nrecords akn_level     access
1                ABATLAS1   123364         5       full
2                ABATLAS2   201398         5       full
3              ABBIRDRECS   357264         5       full
4                  ATOWLS     2778         4 by request
5                     BBS  5735895         5       full
6               BBS50-CAN  3219534         5       full
7           BBS50-US-EAST  8067776         5       full
8           BBS50-US-WEST  8701116         5       full
9           BCATLAS1BE_DO    41412         5       full
10         BCATLAS1BE_RAW   344433         5       full
11        BCATLAS1BE_SUMM   165485         5       full
12             BCATLAS1PC   260647         5       full
13             BCATLAS1RC    21884         3 by request
14                BCBEACH     7263         4 by request
15                  BCCWS   353868         4 by request
16                   BCMA    11291         5       full
17                 BCOWLS    28240         4 by request
18                  BGRMM      476         5       full
19              BIRDSOFBC   498444         2       none
20                    CBC  7570427         2       none
```

The next thing will be to add a vignette that clarifies how a user should determine what data they have access to.
